-- Potion Mixes Table

create table
  public.potion_mixes (
    sku text not null,
    name text not null,
    price integer not null default 0,
    quantity integer not null default 0,
    potion_id integer generated by default as identity,
    formula integer[] not null,
    constraint potion_mixes_pkey primary key (potion_id),
    constraint potion_mixes_potion_id_key unique (potion_id),
    constraint potion_mixes_sku_key unique (sku)
  ) tablespace pg_default;

--  Carts Table

-- Cart Items Table
