-- Potion Mixes Table

create table
  public.potion_mixes (
    sku text not null,
    name text not null,
    price integer not null default 0,
    quantity integer not null default 0,
    potion_id integer generated by default as identity,
    formula integer[] not null,
    constraint potion_mixes_pkey primary key (potion_id),
    constraint potion_mixes_potion_id_key unique (potion_id),
    constraint potion_mixes_sku_key unique (sku)
  ) tablespace pg_default;

--  Carts Table

create table
  public.carts (
    cart_id integer generated by default as identity,
    customer text not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

-- Cart Items Table

create table
  public.cart_items (
    cart_id integer generated by default as identity,
    potion_id integer not null,
    quantity integer not null default 0,
    constraint cart_items_pkey primary key (cart_id, potion_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id) on update restrict on delete cascade,
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_mixes (potion_id) on update restrict on delete cascade
  ) tablespace pg_default;
